FROM python:3.9

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY artifacts artifacts
COPY deploy deploy

EXPOSE 8001

CMD ["uvicorn", "deploy.app:app", "--host", "0.0.0.0", "--port", "8001"]
